# Generated by Django 4.1.2 on 2022-11-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_account_created_at_alter_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remaining_balance',
            field=models.IntegerField(null=True),
        ),
    ]
